# Generated by Django 4.2.2 on 2023-06-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
    ]
