# Generated by Django 4.2.2 on 2023-06-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'コメント', 'verbose_name_plural': 'コメント'},
        ),
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': '放送日', 'verbose_name_plural': '放送日'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name': '番組', 'verbose_name_plural': '番組'},
        ),
    ]
