# Generated by Django 4.2.2 on 2023-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0003_alter_comment_options_alter_date_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name': '6月27日', 'verbose_name_plural': '6月27日'},
        ),
        migrations.AlterField(
            model_name='date',
            name='on_air_date',
            field=models.CharField(max_length=255, verbose_name='放送日'),
        ),
    ]
