# Generated by Django 4.2.2 on 2023-06-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0004_alter_tv_options_alter_date_on_air_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name': '番組タイトル', 'verbose_name_plural': '番組タイトル'},
        ),
    ]
