# Generated by Django 4.2.2 on 2023-06-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0008_alter_tv_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='time',
            field=models.CharField(max_length=5, verbose_name='放送時間'),
        ),
    ]
