# Generated by Django 4.2.2 on 2023-06-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0010_customuser_favorite_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
    ]
