# Generated by Django 4.2.2 on 2023-06-26 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0010_alter_tv_time'),
        ('tvasahi', '0010_customuser_favorite_category'),
    ]

    operations = [
    ]
