# Generated by Django 4.2.2 on 2023-06-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0011_merge_20230626_1109'),
        ('tvasahi', '0012_comment_user_name'),
    ]

    operations = [
    ]
