# Generated by Django 4.2.2 on 2023-06-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0013_alter_comment_user_name'),
        ('tvasahi', '0014_alter_comment_user_name'),
    ]

    operations = [
    ]
