# Generated by Django 4.2.2 on 2023-06-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0014_comment_pub_date'),
        ('tvasahi', '0015_merge_20230627_1306'),
    ]

    operations = [
    ]
