# Generated by Django 4.2.2 on 2023-06-28 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('tvasahi', '0016_merge_0014_comment_pub_date_0015_merge_20230627_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=64, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='カート'),
        ),
    ]
