# Generated by Django 4.2.2 on 2023-06-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_units'),
        ('tvasahi', '0017_customuser_address_customuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=64, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='カート'),
        ),
    ]
