# Generated by Django 4.2.2 on 2023-06-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0019_customuser_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='icon',
        ),
    ]
