# Generated by Django 4.2.2 on 2023-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0020_remove_customuser_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon_images/', verbose_name='アイコン画像'),
        ),
    ]
