# Generated by Django 4.2.2 on 2023-06-29 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0020_remove_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvasahi.tv', verbose_name='紐付く番組名'),
        ),
    ]
