# Generated by Django 4.2.2 on 2023-06-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvasahi', '0021_alter_comment_target'),
        ('tvasahi', '0021_customuser_icon'),
    ]

    operations = [
    ]
