# Generated by Django 4.2.2 on 2023-06-28 02:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='価格')),
                ('description', models.TextField(verbose_name='商品説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images/', verbose_name='商品画像')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='購入時刻')),
                ('purchase_num', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='購入数')),
                ('state_flag', models.BooleanField(default=True, verbose_name='運用状況')),
                ('fk_goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.goods', verbose_name='書籍')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='CartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='購入数')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.goods', verbose_name='書籍')),
            ],
        ),
    ]
