# Generated by Django 4.2.2 on 2023-06-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='management_code',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='release_flag',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='state_flag',
        ),
    ]
