# Generated by Django 4.2.2 on 2023-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goods_management_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='商品名'),
        ),
    ]
